name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "notify"
  notify:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        - name: Get the version
          id: get_version
          run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        - name: Get URL
          run: echo "URL=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases/tag/${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        - name: Send email
          uses: dawidd6/action-send-mail@v2.2.1
          with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{secrets.MAIL_USERNAME}}
            password: ${{secrets.MAIL_PASSWORD}}
            subject: Liberación AgroIoT ${{ github.event.release.tag_name }}
            # Body of mail message (might be a filename prefixed with file:// to read from)
            body: |
              Liberación AgroIoT ${{ github.event.release.name }} disponible en ${{ github.event.release.html_url }}
              Fecha de publicación: ${{github.event.release.published_at}}
              Cambios destacables:
              ${{github.event.release.body}}
            # Recipients mail addresses (separated with comma)
            to: lf@vortexmakes.com,db@vortexmakes.com,truelsegaard@gmail.com 
            # Full name of mail sender (might be with an email address specified in <>)
            from: Yipies AgroIOT bot releaser
            # Content-Type HTTP header (text/html or text/plain)
            #content_type: # optional, default is text/plain
            # Files that will be added to mail message attachments (separated with comma)
